import { beforeEach, describe, expect, it } from "vitest";
import {
  generateUnsubscribeToken,
  validateUnsubscribeToken,
} from "../../../server/email/utils";

describe("email unsubscribe tokens", () => {
  beforeEach(() => {
    process.env.UNSUBSCRIBE_TOKEN_SECRET = "unit-test-unsubscribe-secret";
  });

  it("validates signed unsubscribe tokens generated by the server", () => {
    const token = generateUnsubscribeToken("user-1", "client@example.com");

    expect(validateUnsubscribeToken(token)).toEqual({
      userId: "user-1",
      email: "client@example.com",
    });
  });

  it("rejects signed tokens when the payload is tampered with", () => {
    const token = generateUnsubscribeToken("user-1", "client@example.com");
    const [, signature] = token.split(".");
    const tamperedPayload = Buffer.from(
      JSON.stringify({
        userId: "user-1",
        email: "attacker@example.com",
        timestamp: Date.now(),
      }),
    ).toString("base64url");

    expect(validateUnsubscribeToken(`${tamperedPayload}.${signature}`)).toBeNull();
  });

  it("rejects legacy unsigned tokens with non-email HTML payloads", () => {
    const legacyToken = Buffer.from(
      `user-1:<img src=x onerror=alert(1)>:${Date.now()}`,
    ).toString("base64url");

    expect(validateUnsubscribeToken(legacyToken)).toBeNull();
  });

  it("keeps legacy valid tokens working during the expiry window", () => {
    const legacyToken = Buffer.from(
      `user-1:client@example.com:${Date.now()}`,
    ).toString("base64url");

    expect(validateUnsubscribeToken(legacyToken)).toEqual({
      userId: "user-1",
      email: "client@example.com",
    });
  });
});
