import { usePageTitle } from "@/hooks/use-page-title";
import React, { useEffect, useState } from "react";
import { useRoute } from "wouter";
import { Building2, CalendarClock, CheckCircle, XCircle, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

/**
 * Public visit confirmation page (/v/confirm/:token).
 *
 * The lead reaches this from the WhatsApp/email link generated by
 * server/services/visit-notifications.ts. It is fully public — the token in the URL
 * is the only credential — so requests go to the CSRF-excluded public endpoints:
 *   GET  /api/visits/confirm/:token
 *   POST /api/visits/confirm/:token   { action: "confirm" | "decline" }
 *   POST /api/visits/reschedule/:token { scheduledFor }
 */

interface PublicVisit {
  id: string;
  scheduledFor: string;
  status: string;
  confirmationStatus: string | null;
  propertyId: string;
  notes: string | null;
}

interface PublicProperty {
  id: string;
  title: string | null;
  address: string | null;
  city: string | null;
}

function formatWhen(value: string | null | undefined): string {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString("pt-BR", { dateStyle: "full", timeStyle: "short" });
}

export default function VisitConfirmPage() {
  usePageTitle("Confirmação de Visita");
  const [, params] = useRoute("/v/confirm/:token");
  const token = params?.token ?? "";

  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [visit, setVisit] = useState<PublicVisit | null>(null);
  const [property, setProperty] = useState<PublicProperty | null>(null);

  const [submitting, setSubmitting] = useState<"confirm" | "decline" | "reschedule" | null>(null);
  const [result, setResult] = useState<"confirmed" | "declined" | "rescheduled" | null>(null);
  const [actionError, setActionError] = useState("");

  const [showReschedule, setShowReschedule] = useState(false);
  const [newDate, setNewDate] = useState("");

  useEffect(() => {
    let cancelled = false;
    async function load() {
      if (!token) {
        setLoadError("Link inválido.");
        setLoading(false);
        return;
      }
      try {
        const res = await fetch(`/api/visits/confirm/${encodeURIComponent(token)}`);
        if (!res.ok) {
          setLoadError(
            res.status === 404
              ? "Visita não encontrada. O link pode ter expirado."
              : "Não foi possível carregar a visita.",
          );
          setLoading(false);
          return;
        }
        const data = await res.json();
        if (cancelled) return;
        setVisit(data.visit ?? null);
        setProperty(data.property ?? null);
        if (data.visit?.confirmationStatus === "confirmed") setResult("confirmed");
        if (data.visit?.confirmationStatus === "declined") setResult("declined");
      } catch {
        if (!cancelled) setLoadError("Erro de conexão. Tente novamente.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, [token]);

  async function handleConfirm(action: "confirm" | "decline") {
    setActionError("");
    setSubmitting(action);
    try {
      const res = await fetch(`/api/visits/confirm/${encodeURIComponent(token)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action }),
      });
      if (!res.ok) {
        setActionError("Não foi possível registrar sua resposta. Tente novamente.");
        return;
      }
      setResult(action === "confirm" ? "confirmed" : "declined");
    } catch {
      setActionError("Erro de conexão. Tente novamente.");
    } finally {
      setSubmitting(null);
    }
  }

  async function handleReschedule(e: React.FormEvent) {
    e.preventDefault();
    setActionError("");
    if (!newDate) {
      setActionError("Escolha uma nova data e horário.");
      return;
    }
    setSubmitting("reschedule");
    try {
      const res = await fetch(`/api/visits/reschedule/${encodeURIComponent(token)}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ scheduledFor: new Date(newDate).toISOString() }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        setActionError(
          data?.error || data?.message || "Horário indisponível. Escolha outro horário.",
        );
        return;
      }
      setResult("rescheduled");
    } catch {
      setActionError("Erro de conexão. Tente novamente.");
    } finally {
      setSubmitting(null);
    }
  }

  const propertyLabel = property?.title || property?.address || "o imóvel";

  return (
    <div className="min-h-screen flex items-center justify-center bg-muted/30 px-4 py-10">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
            <Building2 className="h-6 w-6 text-primary" />
          </div>
          <CardTitle>Confirmação de Visita</CardTitle>
          <CardDescription>
            {loading
              ? "Carregando os detalhes da sua visita..."
              : "Confirme, recuse ou reagende sua visita ao imóvel."}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-5">
          {loading && (
            <div className="flex items-center justify-center py-8 text-muted-foreground">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
          )}

          {!loading && loadError && (
            <p className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">
              {loadError}
            </p>
          )}

          {!loading && !loadError && visit && (
            <>
              <div className="rounded-lg border bg-card p-4 text-sm">
                <div className="flex items-start gap-3">
                  <CalendarClock className="mt-0.5 h-5 w-5 text-primary" />
                  <div>
                    <p className="font-medium">{propertyLabel}</p>
                    {property?.city && (
                      <p className="text-muted-foreground">{property.city}</p>
                    )}
                    <p className="mt-1">{formatWhen(visit.scheduledFor)}</p>
                  </div>
                </div>
              </div>

              {result === "confirmed" && (
                <p className="flex items-center gap-2 rounded-md bg-emerald-500/10 px-4 py-3 text-sm text-emerald-700 dark:text-emerald-400">
                  <CheckCircle className="h-5 w-5" /> Visita confirmada. Até breve!
                </p>
              )}
              {result === "declined" && (
                <p className="flex items-center gap-2 rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">
                  <XCircle className="h-5 w-5" /> Visita recusada. Caso queira, reagende
                  abaixo.
                </p>
              )}
              {result === "rescheduled" && (
                <p className="flex items-center gap-2 rounded-md bg-emerald-500/10 px-4 py-3 text-sm text-emerald-700 dark:text-emerald-400">
                  <CheckCircle className="h-5 w-5" /> Reagendamento solicitado. Você
                  receberá uma nova confirmação.
                </p>
              )}

              {actionError && (
                <p className="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">
                  {actionError}
                </p>
              )}

              {result !== "rescheduled" && (
                <>
                  {result !== "confirmed" && (
                    <div className="flex gap-3">
                      <Button
                        className="flex-1"
                        onClick={() => handleConfirm("confirm")}
                        disabled={submitting !== null}
                      >
                        {submitting === "confirm" ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          "Confirmar"
                        )}
                      </Button>
                      <Button
                        variant="outline"
                        className="flex-1"
                        onClick={() => handleConfirm("decline")}
                        disabled={submitting !== null}
                      >
                        {submitting === "decline" ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          "Recusar"
                        )}
                      </Button>
                    </div>
                  )}

                  {!showReschedule ? (
                    <Button
                      variant="ghost"
                      className="w-full"
                      onClick={() => setShowReschedule(true)}
                      disabled={submitting !== null}
                    >
                      Preciso reagendar
                    </Button>
                  ) : (
                    <form onSubmit={handleReschedule} className="space-y-3">
                      <label className="block text-sm font-medium">
                        Nova data e horário
                      </label>
                      <input
                        type="datetime-local"
                        value={newDate}
                        onChange={(e) => setNewDate(e.target.value)}
                        className="w-full rounded-md border bg-background px-3 py-2 text-sm"
                      />
                      <Button type="submit" className="w-full" disabled={submitting !== null}>
                        {submitting === "reschedule" ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          "Solicitar reagendamento"
                        )}
                      </Button>
                    </form>
                  )}
                </>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
